import { Montserrat } from 'next/font/google'
import './global.css'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Evraz',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  )
}
